import { useState, useContext, useEffect } from "react"
import { Alert, View, Text, TouchableOpacity } from "react-native"
import { Header } from "react-native/Libraries/NewAppScreen"
import FooterWithButton from "../../components/footerWithButton"
import { getMenuGroup, extrasPrice, MenuItem } from "../../utils"
import { ManualOrderContext, IngredientTypes } from "./utils"
